return {
  -- "folke/trouble.nvim",
  -- dependencies = { "nvim-tree/nvim-web-devicons", "folke/todo-comments.nvim" },
  -- opts = {
  --   focus = true,
  --   win = { "floating" },
  -- },
  -- cmd = "Trouble",
  -- keys = {
  --   { "<leader>to", "<cmd>Trouble diagnostics toggle<CR>", desc = "Trouble Open trouble workspace diagnostics" },
  --   {
  --     "<leader>xd",
  --     "<cmd>Trouble diagnostics toggle filter.buf=0<CR>",
  --     desc = "Trouble Open document diagnostics",
  --   },
  --   { "<leader>xq", "<cmd>Trouble quickfix toggle<CR>", desc = "Trouble Open quickfix list" },
  --   { "<leader>xl", "<cmd>Trouble loclist toggle<CR>", desc = "Trouble Open location list" },
  --   { "<leader>xt", "<cmd>Trouble todo toggle<CR>", desc = "Trouble Open todos" },
  -- },
  -- config = function()
  --   local todo = require "todo-comments"
  --   local trouble = require "trouble"
  --
  --   trouble.setup {}
  --   todo.setup {}
  -- end,
}
